# Generated by Django 2.2.6 on 2020-09-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtools', '0002_auto_20200916_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='clean_name',
            field=models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name'),
        ),
    ]
